### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Naozumi520** [Naozumi520/Remedy#13]
- [x] Change the app arch to universal, as some Apple Silicon Macs have issues installing remedy.
- [x] Disable overflow
- [x] Update to the latest electron? (New overlay method available since Electron v21)
- [x] Fix ARM64
- [ ] Fix QR Code login doesn't do anything

**Comment by Naozumi520** [comment]
Moved to #17
