### ISSUE TITLE
2.0 roadmap

### ISSUE THREAD

**Issue by Naozumi520** [Naozumi520/Remedy#17]
- [x] Replace login method with web login
- [x] Add chat overlay shortcut similar to windows'
- [x] Change the app arch to universal, as some Apple Silicon Macs have issues installing remedy.
- [x] Disable overflow
- [x] Update to the latest electron? (New overlay method available since Electron v21)
- [x] Fix ARM64 #12 
- [x] Fix QR Code login doesn't do anything #14
